### PR TITLE
event handlers, click/keypress to delete, multi-select, drag area to multi-select

### PR DESCRIPTION
**Pull request by therewasaguy**
- click on a connection to highlight, twice to delete
  - added this._highlightedConnection to keep track of highlighted connection
  - added .cnxn class with z-index so that connections are clickable
  - to do: add an X in the middle of the connection
- add keypress handler so that 'delete' key can delete any selected connection / elements
- click in an empty space on the svg canvas to deselect any selected connection / elements
- `_selWrapper` --> `_selWrappers [ ]`  array to allow selecting groups of elements
- drag on canvas to create a selection rectangle. Will select any intersecting elements on `dragEndSVG()`
- multiple elements can be dragged...sort of. @sepans can you take a look at `_dragWrapper()` and `_dragWrapperTarget()`?

### CODE REVIEW

**Comment by sepans** [comment]
Great! thanks a lot. I am looking at it.

**Comment by sepans** [comment]
I was thinking one other very useful feature would be an infinite canvas. So then we will need a grab-and-move-canvas functionality. Maybe holding down the command button switches between grab-and-move and drag-and-select.

**Comment by therewasaguy** [comment]
yes, Lenses should be able to zoom!

**Comment by sepans** [comment]
I am going to split this branch/PR into two and merge one first. Already overwhelmed :)

**Comment by sepans** [comment]
merged here: https://github.com/lenses/lenses-freeform/pull/4

**Comment by sepans** [comment]
and here: https://github.com/lenses/lenses-freeform/pull/3 (delete element)

**Pull request closed without merging**
